version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d

  dockergen:
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  #whoami:
    #image: jwilder/whoami
    #environment:
      #- VIRTUAL_HOST=local

  # grafana:
  #   image: grafana/grafana-oss:latest
  #   container_name: grafana
  #   restart: unless-stopped
  #   environment:
  #     - VIRTUAL_HOST=local
  #     - GF_LOG_LEVEL=debug
  #   ports: 
  #     - "3000:3000"
  #   volumes:
  #     - 'grafana_storage:/var/lib/grafana'
      
  # volumes:
  #   grafana_storage: {}
